import json
import os
import shutil
import tempfile
import unittest
from pathlib import Path

from bodesign_workflow_core import C00TemplateError, assess_c00_prd_readiness, c00_update_answers, emit_c00_prd_markdown, load_c00_prd_rubric, load_c00_prd_template, scaffold_c00_prd_package
from bodesign_workflow_core.requirement_planning import C00_REQUIREMENT_FIELD_BINDINGS, RequirementFieldBinding, validate_requirement_bindings


PRIVATE_BASE = Path(os.environ.get("XDG_RUNTIME_DIR") or (Path.home() / ".cache")) / "claude-work"


class C00PrdTemplateTests(unittest.TestCase):
    def setUp(self):
        PRIVATE_BASE.mkdir(parents=True, exist_ok=True)
        self.work = Path(tempfile.mkdtemp(prefix="bodesign-c00-", dir=PRIVATE_BASE))

    def tearDown(self):
        shutil.rmtree(self.work, ignore_errors=True)

    def _a_field_key(self):
        st = json.loads((self.work / "C00-PRD" / "answer_state.json").read_text())
        sec = next(iter(st["documents"].values()))["sections"][0]
        return sec["id"], next(iter(sec["fields"]))

    def test_update_answers_records_and_recomputes(self):
        scaffold_c00_prd_package(self.work, project_name="aiguard", include_rf=False)
        sid, fk = self._a_field_key()
        res = c00_update_answers(self.work, {fk: "OV5640 camera + Wi-Fi + USB-C", "nope_field": "x"})
        self.assertIn(fk, res.updated)
        self.assertIn("nope_field", res.not_found)  # unknown key reported, not guessed
        st = json.loads((self.work / "C00-PRD" / "answer_state.json").read_text())
        field = next(iter(st["documents"].values()))["sections"][0]["fields"][fk]
        self.assertEqual(field["state"], "answered")
        self.assertEqual(field["value"], "OV5640 camera + Wi-Fi + USB-C")
        self.assertEqual(field["source"], "user")
        self.assertTrue(res.emitted_files)  # PRD regenerated by default

    def test_update_answers_supports_state_and_qualified_key(self):
        scaffold_c00_prd_package(self.work, project_name="aiguard", include_rf=False)
        sid, fk = self._a_field_key()
        res = c00_update_answers(self.work, {f"{sid}.{fk}": {"value": "TBD by lab", "state": "external-needed"}},
                                 regenerate=False)
        self.assertIn(f"{sid}.{fk}", res.updated)
        st = json.loads((self.work / "C00-PRD" / "answer_state.json").read_text())
        self.assertEqual(next(iter(st["documents"].values()))["sections"][0]["fields"][fk]["state"], "external-needed")

    def test_update_answers_fails_fast(self):
        with self.assertRaises(C00TemplateError):
            c00_update_answers(self.work, {"x": "y"})  # not scaffolded
        scaffold_c00_prd_package(self.work, project_name="aiguard", include_rf=False)
        with self.assertRaises(C00TemplateError):
            c00_update_answers(self.work, {})  # empty answers
        sid, fk = self._a_field_key()
        with self.assertRaises(C00TemplateError):
            c00_update_answers(self.work, {fk: {"value": "x", "state": "bogus"}})  # invalid state

    def test_loads_committed_prd_template(self):
        template = load_c00_prd_template()

        self.assertGreaterEqual(len(template.project_sections), 12)
        self.assertGreaterEqual(len(template.rf_sections), 3)
        self.assertIn("Project_Requirements.md", template.to_dict()["documents"])
        first = template.project_sections[0]
        self.assertEqual("s01_business_strategy", first["id"])
        self.assertTrue(first["required_fields"])
        self.assertTrue(first["consultant_prompts"])
        self.assertTrue(first["handoff_targets"])

    def test_loads_committed_prd_rubric(self):
        rubric = load_c00_prd_rubric()
        data = rubric.data

        self.assertIn("answered", data["field_states"])
        self.assertIn("accepted-risk", data["scoring_policy"]["complete_states"])
        self.assertIn("business_contract", rubric.to_dict()["document_gates"])
        self.assertIn("C03", rubric.to_dict()["downstream_targets"])

    def test_requirement_planning_fields_are_bound_to_c00_template(self):
        template = load_c00_prd_template()

        validate_requirement_bindings(template.data)

        binding_by_key = {binding.key: binding for binding in C00_REQUIREMENT_FIELD_BINDINGS}
        self.assertEqual({"compute", "comms", "memory", "power_input", "charging", "battery", "dimensions", "certification", "volume"}, set(binding_by_key))
        self.assertEqual(("s06_electrical_requirements", "compute"), (binding_by_key["compute"].section_id, binding_by_key["compute"].field))
        self.assertEqual(("s05_id_me_requirements", "dimensions"), (binding_by_key["dimensions"].section_id, binding_by_key["dimensions"].field))
        self.assertTrue(binding_by_key["volume"].binding_note)

    def test_requirement_binding_missing_field_fails_fast(self):
        template = load_c00_prd_template()
        bad_binding = (RequirementFieldBinding("bad", "s06_electrical_requirements", "missing_field", "Bad", ("bad",), "Bad?"),)

        with self.assertRaises(ValueError) as context:
            validate_requirement_bindings(template.data, bad_binding)

        self.assertIn("missing C00 field", str(context.exception))

    def test_missing_template_fails_fast(self):
        with self.assertRaises(C00TemplateError):
            load_c00_prd_template(self.work / "missing.json")

    def test_invalid_template_shape_fails_fast(self):
        path = self.work / "bad_template.json"
        path.write_text(json.dumps({"documents": [{"file": "Project_Requirements.md", "sections": [{"id": "s01", "title": "Bad"}]}]}), encoding="utf-8")

        with self.assertRaises(C00TemplateError) as context:
            load_c00_prd_template(path)

        self.assertIn("required_fields", str(context.exception))

    def test_invalid_rubric_shape_fails_fast(self):
        path = self.work / "bad_rubric.json"
        path.write_text(json.dumps({"field_states": {"answered": "ok"}}), encoding="utf-8")

        with self.assertRaises(C00TemplateError) as context:
            load_c00_prd_rubric(path)

        self.assertIn("document_gates", str(context.exception))

    def test_scaffold_creates_project_prd_and_missing_answer_state(self):
        result = scaffold_c00_prd_package(self.work, project_name="C00 POC")

        self.assertEqual("scaffold_created", result.status)
        self.assertFalse(result.to_dict()["readiness_computed"])
        self.assertFalse(result.to_dict()["prd_emitted"])
        self.assertFalse(result.to_dict()["human_approved"])
        self.assertIn("C00-PRD/Project_Requirements.md", result.files)
        self.assertIn("C00-PRD/answer_state.json", result.files)
        self.assertNotIn("C00-PRD/RF_Requirements.md", result.files)
        project = (self.work / "C00-PRD" / "Project_Requirements.md").read_text(encoding="utf-8")
        self.assertIn("Project: C00 POC", project)
        self.assertIn("State: `missing`", project)
        self.assertIn("{missing}", project)
        state = json.loads((self.work / "C00-PRD" / "answer_state.json").read_text(encoding="utf-8"))
        self.assertFalse(state["readiness_computed"])
        self.assertFalse(state["prd_emitted"])
        self.assertIn("Project_Requirements.md", state["documents"])
        self.assertNotIn("RF_Requirements.md", state["documents"])
        first_section = state["documents"]["Project_Requirements.md"]["sections"][0]
        self.assertEqual("missing", first_section["state"])
        self.assertTrue(first_section["fields"])
        self.assertTrue(all(field["state"] == "missing" for field in first_section["fields"].values()))

    def test_scaffold_include_rf_creates_rf_source_and_state(self):
        result = scaffold_c00_prd_package(self.work, include_rf=True)

        self.assertIn("C00-PRD/RF_Requirements.md", result.files)
        self.assertGreaterEqual(result.rf_section_count, 3)
        self.assertTrue((self.work / "C00-PRD" / "RF_Requirements.md").exists())
        state = json.loads((self.work / "C00-PRD" / "answer_state.json").read_text(encoding="utf-8"))
        self.assertTrue(state["include_rf"])
        self.assertIn("RF_Requirements.md", state["documents"])
        rf_sections = state["documents"]["RF_Requirements.md"]["sections"]
        self.assertTrue(rf_sections)
        self.assertTrue(all(section["state"] == "missing" for section in rf_sections))

    def test_readiness_scaffold_only_is_blocked_with_next_question(self):
        scaffold_c00_prd_package(self.work)

        readiness = assess_c00_prd_readiness(self.work)

        self.assertEqual("blocked", readiness.status)
        self.assertEqual(0, readiness.readiness_pct)
        self.assertGreater(readiness.field_counts["blocking"], 0)
        self.assertTrue(readiness.next_question)
        self.assertFalse(readiness.to_dict()["prd_emitted"])
        self.assertFalse(readiness.to_dict()["human_approved"])

    def test_readiness_counts_answered_and_accepted_risk_as_complete(self):
        scaffold_c00_prd_package(self.work)
        state_path = self.work / "C00-PRD" / "answer_state.json"
        state = json.loads(state_path.read_text(encoding="utf-8"))
        fields = state["documents"]["Project_Requirements.md"]["sections"][0]["fields"]
        first_key = next(iter(fields))
        fields[first_key]["state"] = "answered"
        fields[first_key]["value"] = "Founder-led edge AI product"
        second_key = next(key for key in fields if key != first_key)
        fields[second_key]["state"] = "accepted-risk"
        fields[second_key]["value"] = "Proceed without customer validation for POC"
        state_path.write_text(json.dumps(state, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

        readiness = assess_c00_prd_readiness(self.work)

        self.assertEqual(2, readiness.field_counts["complete"])
        self.assertGreater(readiness.readiness_pct, 0)
        self.assertEqual("blocked", readiness.status)

    def test_readiness_missing_answer_state_fails_fast(self):
        with self.assertRaises(C00TemplateError):
            assess_c00_prd_readiness(self.work)

    def test_emit_markdown_preserves_field_states_and_handoff(self):
        scaffold_c00_prd_package(self.work, project_name="C00 POC", include_rf=True)
        state_path = self.work / "C00-PRD" / "answer_state.json"
        state = json.loads(state_path.read_text(encoding="utf-8"))
        fields = state["documents"]["Project_Requirements.md"]["sections"][0]["fields"]
        first_key = next(iter(fields))
        fields[first_key]["state"] = "answered"
        fields[first_key]["value"] = "Founder-led edge AI device"
        fields[first_key]["source"] = "user-interview"
        second_key = next(key for key in fields if key != first_key)
        fields[second_key]["state"] = "external-needed"
        fields[second_key]["value"] = "Needs customer validation"
        fields[second_key]["owner"] = "external"
        state_path.write_text(json.dumps(state, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

        result = emit_c00_prd_markdown(self.work)

        self.assertEqual("prd_markdown_emitted", result.status)
        self.assertTrue(result.to_dict()["prd_emitted"])
        self.assertFalse(result.to_dict()["human_approved"])
        self.assertIn("C00-PRD/Project_Requirements.generated.md", result.files)
        self.assertIn("C00-PRD/RF_Requirements.generated.md", result.files)
        self.assertIn("C00-PRD/C00_Handoff_Report.md", result.files)
        project = (self.work / "C00-PRD" / "Project_Requirements.generated.md").read_text(encoding="utf-8")
        self.assertIn("Founder-led edge AI device", project)
        self.assertIn("state: `answered`", project)
        self.assertIn("source: `user-interview`", project)
        self.assertIn("Needs customer validation _[external-needed]_", project)
        self.assertIn("{missing}", project)
        handoff = (self.work / "C00-PRD" / "C00_Handoff_Report.md").read_text(encoding="utf-8")
        self.assertIn("Readiness:", handoff)
        self.assertIn("Downstream Handoff Gates", handoff)


if __name__ == "__main__":
    unittest.main()
